parameters:


services:
    gearman.command.generate_workers_config:
        class: DreamCommerce\GearmanBundle\Command\GenerateWorkersConfigCommand
        tags:
            - { name: console.command }
