parameters:
    gearman.execute.class: DreamCommerce\GearmanBundle\Service\GearmanExecute

services:
#    dream_commerce_gearman.example:
#        class: DreamCommerce\GearmanBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
